#Requires -Version 5.1
<#
.SYNOPSIS
  Expose local closed-beta on live HTTPS via Cloudflare Tunnel (or ngrok).

.DESCRIPTION
  Prerequisites: local closed-beta already PASS (Postgres, BETA_ALLOW_DRAFT,
  pnpm dev on :3000 with /api/health + /api/ready 200).

  Starts a free quick tunnel (default) or a named Cloudflare tunnel, prints the
  public https URL, reminds BASE_URL / Better Auth trusted-origin settings, and
  smokes health/ready against the tunnel URL.

  Tunnel != Vercel production. Does not invent Neon/Vercel secrets.
  Does not claim PUBLISHED / JPJO.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts/tunnel-closed-beta.ps1
  powershell -ExecutionPolicy Bypass -File scripts/tunnel-closed-beta.ps1 -Provider ngrok
  powershell -ExecutionPolicy Bypass -File scripts/tunnel-closed-beta.ps1 -NamedTunnel slowarium -Hostname beta.example.com
#>

param(
  [ValidateSet("cloudflared", "ngrok")]
  [string]$Provider = "cloudflared",

  [int]$LocalPort = 3000,

  [string]$NamedTunnel = "",

  [string]$Hostname = "",

  [int]$SmokeWaitSeconds = 90,

  [int]$UrlWaitSeconds = 45,

  [switch]$SkipLocalCheck,

  [switch]$Detach
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$WebDir = Join-Path $RepoRoot "web"
$EnvLocal = Join-Path $WebDir ".env.local"
$EnvTunnel = Join-Path $WebDir ".env.tunnel.local"
$LocalBase = "http://127.0.0.1:$LocalPort"

function Ok([string]$Msg) { Write-Host ("  [OK]  " + $Msg) -ForegroundColor Green }
function Bad([string]$Msg) { Write-Host ("  [FAIL] " + $Msg) -ForegroundColor Red }
function Note([string]$Msg) { Write-Host ("  [..]  " + $Msg) -ForegroundColor DarkGray }
function WarnMsg([string]$Msg) { Write-Host ("  [WARN] " + $Msg) -ForegroundColor Yellow }

function Test-Http200([string]$Url) {
  try {
    $r = Invoke-WebRequest -Uri $Url -Method GET -UseBasicParsing -TimeoutSec 8
    return ($r.StatusCode -eq 200)
  } catch {
    return $false
  }
}

function Resolve-HostViaPublicDns([string]$Hostname) {
  foreach ($server in @("1.1.1.1", "8.8.8.8")) {
    try {
      $answers = Resolve-DnsName -Name $Hostname -Type A -Server $server -DnsOnly -ErrorAction Stop
      $ip = @($answers | Where-Object { $_.Type -eq "A" } | Select-Object -ExpandProperty IPAddress -First 1)
      if ($ip) { return [string]$ip }
    } catch { }
  }
  return $null
}

function Test-Http200Robust([string]$Url) {
  if (Test-Http200 $Url) { return $true }
  # Some home routers fail to resolve *.trycloudflare.com; fall back to public DNS + curl --resolve
  try {
    $u = [Uri]$Url
    if ($u.Scheme -ne "https") { return $false }
    $ip = Resolve-HostViaPublicDns $u.Host
    if (-not $ip) { return $false }
    $port = if ($u.IsDefaultPort) { 443 } else { $u.Port }
    $resolve = "{0}:{1}:{2}" -f $u.Host, $port, $ip
    & curl.exe -fsS --max-time 15 --resolve $resolve $Url 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Note ("smoke via public DNS ($ip) - local resolver could not find " + $u.Host)
      return $true
    }
  } catch { }
  return $false
}

function Get-EnvLocalValue([string]$Key) {
  if (-not (Test-Path $EnvLocal)) { return $null }
  $line = Get-Content -LiteralPath $EnvLocal -ErrorAction SilentlyContinue |
    Where-Object { $_ -match ("^\s*" + [regex]::Escape($Key) + "\s*=") } |
    Select-Object -First 1
  if (-not $line) { return $null }
  return (($line -split "=", 2)[1]).Trim().Trim('"').Trim("'")
}

function Find-Cloudflared {
  $cmd = Get-Command cloudflared -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $candidates = @(
    "${env:ProgramFiles(x86)}\cloudflared\cloudflared.exe",
    "${env:ProgramFiles}\cloudflared\cloudflared.exe",
    "$env:LOCALAPPDATA\cloudflared\cloudflared.exe"
  )
  foreach ($c in $candidates) {
    if ($c -and (Test-Path -LiteralPath $c)) { return $c }
  }
  return $null
}

function Find-Ngrok {
  $cmd = Get-Command ngrok -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  return $null
}

function Show-CloudflaredInstall {
  Write-Host ""
  Bad "cloudflared not found on PATH"
  Write-Host "  Install (pick one), then re-run this script:" -ForegroundColor Yellow
  Write-Host "    winget install --id Cloudflare.cloudflared -e" -ForegroundColor Cyan
  Write-Host "    # or download: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/" -ForegroundColor DarkGray
  Write-Host "  Alternate: -Provider ngrok (requires ngrok auth token once)" -ForegroundColor DarkGray
  Write-Host ""
}

function Write-TunnelEnvFile([string]$PublicUrl) {
  $body = @"
# Generated by scripts/tunnel-closed-beta.ps1 - gitignored (.env.*).
# Merge into the shell that runs ``pnpm --dir web dev`` (restart required for NEXT_PUBLIC_*).
# Do NOT copy ALLOW_DEV_TUNNEL_ORIGINS onto Vercel.

ALLOW_DEV_TUNNEL_ORIGINS=true
BETTER_AUTH_URL=$PublicUrl
NEXT_PUBLIC_APP_URL=$PublicUrl
APP_URL=$PublicUrl
# Optional explicit allow-list (comma-separated). Wildcards also come from ALLOW_DEV_TUNNEL_ORIGINS.
# TRUSTED_ORIGINS=$PublicUrl
"@
  Set-Content -LiteralPath $EnvTunnel -Value $body -Encoding UTF8
  Ok ("wrote " + $EnvTunnel)
}

function Show-AuthReminders([string]$PublicUrl) {
  Write-Host ""
  Write-Host "  Auth / cookie reminders (login through tunnel)" -ForegroundColor Cyan
  Note "Public URL: $PublicUrl"
  Note "Prefer: set ALLOW_DEV_TUNNEL_ORIGINS=true in web/.env.local (local only; never on Vercel)"
  Note "For Secure cookies + Better Auth baseURL, restart pnpm dev with tunnel URL as BETTER_AUTH_URL / NEXT_PUBLIC_APP_URL / APP_URL"
  Write-Host "  PowerShell restart example:" -ForegroundColor DarkGray
  Write-Host "    cd $WebDir" -ForegroundColor Cyan
  Write-Host "    `$env:ALLOW_DEV_TUNNEL_ORIGINS='true'" -ForegroundColor Cyan
  Write-Host "    `$env:BETTER_AUTH_URL='$PublicUrl'" -ForegroundColor Cyan
  Write-Host "    `$env:NEXT_PUBLIC_APP_URL='$PublicUrl'" -ForegroundColor Cyan
  Write-Host "    `$env:APP_URL='$PublicUrl'" -ForegroundColor Cyan
  Write-Host "    pnpm dev" -ForegroundColor Cyan
  Note "Snippet also written to web/.env.tunnel.local (gitignored)"
  Write-Host ""
}

function Invoke-TunnelSmoke([string]$PublicUrl) {
  $base = $PublicUrl.TrimEnd("/")
  Write-Host "  Smoke: health + ready on tunnel" -ForegroundColor Cyan
  $deadline = [DateTime]::UtcNow.AddSeconds([Math]::Max(1, $SmokeWaitSeconds))
  $attempt = 0
  while ([DateTime]::UtcNow -lt $deadline) {
    $attempt++
    $h = Test-Http200Robust "$base/api/health"
    $r = Test-Http200Robust "$base/api/ready"
    if ($h -and $r) {
      Ok ("health + ready HTTP 200 via tunnel (attempt $attempt)")
      return $true
    }
    $parts = @()
    if (-not $h) { $parts += "health" }
    if (-not $r) { $parts += "ready" }
    Note ("attempt $attempt - waiting on: " + ($parts -join ", "))
    Start-Sleep -Seconds 2
  }
  Bad "tunnel smoke FAILED within ${SmokeWaitSeconds}s"
  Note "Manual: curl.exe -fsS `"$base/api/health`"; curl.exe -fsS `"$base/api/ready`""
  return $false
}

Write-Host ""
Write-Host "  SLOWARIUM - closed-beta HTTPS tunnel" -ForegroundColor Cyan
Write-Host ("  Repo: " + $RepoRoot) -ForegroundColor DarkGray
Write-Host "  Alternate to Vercel/Neon. Does not invent secrets. Does not claim PUBLISHED / JPJO." -ForegroundColor DarkGray
Write-Host ""

# --- Prerequisites ---
if (-not $SkipLocalCheck) {
  Write-Host "  * Local closed-beta prerequisites" -ForegroundColor Cyan
  $healthOk = Test-Http200 "$LocalBase/api/health"
  $readyOk = Test-Http200 "$LocalBase/api/ready"
  if ($healthOk) { Ok "GET $LocalBase/api/health -> 200" } else { Bad "GET $LocalBase/api/health failed" }
  if ($readyOk) { Ok "GET $LocalBase/api/ready -> 200" } else { Bad "GET $LocalBase/api/ready failed" }

  if (-not (Test-Path $EnvLocal)) {
    WarnMsg "web/.env.local missing - see docs/operations/local-closed-beta.md"
  } else {
    $draft = Get-EnvLocalValue "BETA_ALLOW_DRAFT"
    if ($draft -eq "true" -or $draft -eq "1") {
      Ok "BETA_ALLOW_DRAFT=true in .env.local"
    } else {
      WarnMsg "BETA_ALLOW_DRAFT not true in .env.local (closed-beta contract expects true)"
    }
    $tunnelFlag = Get-EnvLocalValue "ALLOW_DEV_TUNNEL_ORIGINS"
    if ($tunnelFlag -eq "true" -or $tunnelFlag -eq "1") {
      Ok "ALLOW_DEV_TUNNEL_ORIGINS=true (tunnel login Origin trust enabled)"
    } else {
      WarnMsg "ALLOW_DEV_TUNNEL_ORIGINS not set - add to .env.local and restart pnpm dev for tunnel login"
    }
  }

  if (-not ($healthOk -and $readyOk)) {
    Write-Host ""
    Bad "Local closed-beta is not PASS on port $LocalPort."
    Write-Host "  Fix first (see docs/operations/local-closed-beta.md):" -ForegroundColor Yellow
    Write-Host "    docker compose up -d postgres" -ForegroundColor Cyan
    Write-Host "    cd web; pnpm dev" -ForegroundColor Cyan
    Write-Host "  Then re-run this script. (Use -SkipLocalCheck only to debug the tunnel itself.)" -ForegroundColor DarkGray
    Write-Host ""
    exit 1
  }
  Write-Host ""
} else {
  WarnMsg "SkipLocalCheck set - not verifying local health/ready"
}

$publicUrl = $null
$proc = $null
$logId = [Guid]::NewGuid().ToString("n")
$logOut = Join-Path $env:TEMP ("slowarium-tunnel-" + $logId + ".out.log")
$logErr = Join-Path $env:TEMP ("slowarium-tunnel-" + $logId + ".err.log")

function Read-TunnelLogs {
  $chunks = @()
  foreach ($f in @($logOut, $logErr)) {
    if (Test-Path -LiteralPath $f) {
      $c = Get-Content -LiteralPath $f -Raw -ErrorAction SilentlyContinue
      if ($c) { $chunks += $c }
    }
  }
  return ($chunks -join "`n")
}

function Show-TunnelLogTail([int]$Lines = 40) {
  $text = Read-TunnelLogs
  if (-not $text) { return }
  ($text -split "`r?`n") | Select-Object -Last $Lines | ForEach-Object { Note $_ }
}

try {
  if ($Provider -eq "cloudflared") {
    $cf = Find-Cloudflared
    if (-not $cf) {
      Show-CloudflaredInstall
      exit 1
    }
    Ok ("cloudflared: " + $cf)
    try {
      $ver = & $cf --version 2>&1 | Out-String
      Note ($ver.Trim())
    } catch { }

    $cfArgs = @()
    if ($NamedTunnel) {
      if (-not $Hostname) {
        Bad "Named tunnel requires -Hostname (public https host)"
        exit 1
      }
      $hostClean = $Hostname.Trim().TrimEnd("/")
      if ($hostClean -match "^https?://") {
        $publicUrl = $hostClean.TrimEnd("/")
      } else {
        $publicUrl = "https://" + $hostClean
      }
      Note "Named tunnel '$NamedTunnel' -> $publicUrl"
      # cloudflared tunnel run <name>  (ingress/hostname must already be configured)
      $cfArgs = @("tunnel", "--no-autoupdate", "run", $NamedTunnel)
    } else {
      Note "Starting Cloudflare quick tunnel -> $LocalBase"
      $cfArgs = @("tunnel", "--no-autoupdate", "--url", $LocalBase)
    }

    $proc = Start-Process -FilePath $cf -ArgumentList $cfArgs `
      -RedirectStandardOutput $logOut -RedirectStandardError $logErr `
      -PassThru -WindowStyle Hidden

    if ($NamedTunnel -and $Hostname) {
      # URL known; wait briefly for process to stay up
      Start-Sleep -Seconds 2
      if ($proc.HasExited) {
        Bad "cloudflared exited early (named tunnel). Check config / login: cloudflared tunnel list"
        Show-TunnelLogTail 30
        exit 1
      }
    } else {
      Write-Host "  Waiting for trycloudflare.com URL..." -ForegroundColor DarkGray
      $deadline = [DateTime]::UtcNow.AddSeconds([Math]::Max(5, $UrlWaitSeconds))
      while ([DateTime]::UtcNow -lt $deadline -and -not $publicUrl) {
        if ($proc.HasExited) {
          Bad "cloudflared exited before publishing a URL"
          Show-TunnelLogTail 40
          exit 1
        }
        $text = Read-TunnelLogs
        if ($text) {
          $m = [regex]::Match($text, "https://[a-zA-Z0-9.-]+\.trycloudflare\.com")
          if ($m.Success) { $publicUrl = $m.Value.TrimEnd("/") }
        }
        if (-not $publicUrl) { Start-Sleep -Milliseconds 500 }
      }
      if (-not $publicUrl) {
        Bad "Timed out waiting for quick-tunnel URL (${UrlWaitSeconds}s)"
        Show-TunnelLogTail 40
        exit 1
      }
    }
  }
  else {
    # ngrok fallback
    $ng = Find-Ngrok
    if (-not $ng) {
      Bad "ngrok not found on PATH"
      Write-Host "  Install ngrok, run ``ngrok config add-authtoken <token>``, then re-run with -Provider ngrok" -ForegroundColor Yellow
      exit 1
    }
    Ok ("ngrok: " + $ng)
    Note "Starting ngrok http $LocalPort"
    $proc = Start-Process -FilePath $ng -ArgumentList @("http", "$LocalPort", "--log=stdout", "--log-format=logfmt") `
      -RedirectStandardOutput $logOut -RedirectStandardError $logErr `
      -PassThru -WindowStyle Hidden

    $deadline = [DateTime]::UtcNow.AddSeconds([Math]::Max(5, $UrlWaitSeconds))
    while ([DateTime]::UtcNow -lt $deadline -and -not $publicUrl) {
      if ($proc.HasExited) {
        Bad "ngrok exited before publishing a URL (auth token missing?)"
        Show-TunnelLogTail 40
        exit 1
      }
      # Prefer local ngrok API
      try {
        $api = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 2
        $https = @($api.tunnels | Where-Object { $_.public_url -like "https://*" } | Select-Object -First 1)
        if ($https -and $https.public_url) {
          $publicUrl = ([string]$https.public_url).TrimEnd("/")
        }
      } catch { }
      if (-not $publicUrl) {
        $text = Read-TunnelLogs
        if ($text) {
          $m = [regex]::Match($text, "https://[a-zA-Z0-9.-]+\.ngrok(?:-free)?\.(?:app|dev|io)")
          if ($m.Success) { $publicUrl = $m.Value.TrimEnd("/") }
        }
      }
      if (-not $publicUrl) { Start-Sleep -Milliseconds 500 }
    }
    if (-not $publicUrl) {
      Bad "Timed out waiting for ngrok https URL"
      exit 1
    }
  }

  Write-Host ""
  Ok ("Public HTTPS URL: " + $publicUrl)
  Write-TunnelEnvFile $publicUrl
  Show-AuthReminders $publicUrl

  $smokeOk = Invoke-TunnelSmoke $publicUrl
  Write-Host ""
  if ($smokeOk) {
    Write-Host "  Done: tunnel smoke PASS on $publicUrl" -ForegroundColor Green
    Write-Host "  Paste (honest): tunnel HTTPS health/ready 200 - not Vercel/Neon production." -ForegroundColor DarkGray
    Write-Host "  Next (human): open URL -> sign-in / invite -> one DRAFT lesson. Still EXTERNAL: Neon+Vercel, JPJO." -ForegroundColor DarkGray
  } else {
    Write-Host "  Blocked: tunnel URL captured but health/ready smoke failed." -ForegroundColor Yellow
    Write-Host "  Check local pnpm dev still up; wait for DNS; restart with auth URL env if login fails." -ForegroundColor Yellow
  }

  if ($Detach) {
    Write-Host ""
    Note ("Tunnel left running (PID $($proc.Id)). Logs: $logOut | $logErr")
    Note "Stop later: Stop-Process -Id $($proc.Id) -Force"
    Write-Host ""
    if ($smokeOk) { exit 0 } else { exit 2 }
  }

  Write-Host ""
  Write-Host "  Tunnel running - press Ctrl+C to stop." -ForegroundColor Cyan
  Write-Host ("  Logs: " + $logOut + " | " + $logErr) -ForegroundColor DarkGray
  Write-Host ""
  try {
    while (-not $proc.HasExited) {
      Start-Sleep -Seconds 2
    }
    WarnMsg "Tunnel process exited (code $($proc.ExitCode))"
  } finally {
    # Ctrl+C lands here on some hosts; ensure cleanup below
  }
  if ($smokeOk) { exit 0 } else { exit 2 }
}
finally {
  if ($proc -and -not $proc.HasExited -and -not $Detach) {
    Note "Stopping tunnel (PID $($proc.Id))..."
    try { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue } catch { }
  }
}
